spring.application.name=peertubeminer
server.port = ${PORT:8081}
peertubeminer.baseuri=https://peertube2.cpy.re/api/v1
peertubeminer.maxVideos=10
peertubeminer.maxComments=2
videominer.uri=${VIDEOMINER_URL:http://localhost:8080}